# ===================================================
# Smart Campus Operations Hub - Application Config
# IT3030 PAF Assignment 2026
# ===================================================

# Server
server.port=8081

# MongoDB - Replace with your own connection string
spring.data.mongodb.uri=mongodb+srv://admin:admin12345@cluster0.fkmou3y.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smart_campus

# JWT Configuration
app.jwt.secret=32b0e9660777cd502b2800f571a68dfdc62ac06122061d9c0f4ed100ed42ddcc49b135df985de56fd205e1d2bd12726513beab40b702f6ccced8bc21659ee182
app.jwt.expiration-ms= 604800000    

# Google OAuth2 - Replace with your Google credentials
spring.security.oauth2.client.registration.google.client-id=940016966683-0e51kdsi94hj67adr2p2knctnqe712sr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# File Upload (for ticket attachments - Module C)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

# Allowed Origins (React dev server)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# OAuth2 redirect after login
app.oauth2.redirect-uri=http://localhost:5173/oauth2/callback

# Logging
logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.security=INFO

# Upload Configuration
app.upload.dir=uploads/tickets
app.upload.static-path=/api/uploads/**

# Jackson Configuration
spring.jackson.serialization.write-durations-as-timestamps=false
